:- include('fakta.pl').
:- include('startGame.pl').
:- include('endGame.pl').
:- include('mainkanKartu.pl').
:- include('lihatKartu.pl').
:- include('lihatCommand.pl').
:- include('cekInfo.pl').
:- include('ambilKartu.pl').
:- include('tantang.pl').
:- include('tangkap.pl').
